name = "learning-example"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.17"
build_base_image = "golang:1.17.8-buster"
enable_go_build_cache = true

[builders."docker:generic"]
enabled = true
build_base_image = "golang:1.17.8-buster"
go_version = "1.17"
# builder cache is disabled because it cannot be used when using a custom build image
enable_go_build_cache = false

[builders."docker:generic".build_args]
GO_PROXY = "https://proxy.golang.org"
RABBIT_URL = "rabbitmq"

[builders."exec:go"]
enabled = true
go_version = "1.17"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "basic"
instances = { min = 5, max = 5, default = 5 }

[[testcases]]
name = "rabbit-1to1"
instances = { min = 2, max = 2, default = 2 }

      [testcases.params]
        # an simple parameter in this test case: you can specify a different value from the command line
        # e.g. --test-param messages=20
        messages   = { type = "int", default = 50 }

[[testcases]]
name = "rabbit-4to1"
instances = { min = 4, max = 4, default = 4 }

[[testcases]]
name = "rabbit-failing-timeout"
instances = { min = 2, max = 2, default = 2 }

[[testcases]]
name = "rabbit-failing-policy"
instances = { min = 2, max = 2, default = 2 }

[[testcases]]
name = "tg-sync-1to1"
instances = { min = 2, max = 2, default = 2 }

[[testcases]]
name = "tg-sync-manyto1"
instances = { min = 2, max = 10, default = 5 }